/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is checked in here
// so TypeScript-aware editors understand the app before dependencies are installed.
